# Generated by Django 4.0.5 on 2022-07-10 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Themes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True, verbose_name='Название темы')),
                ('slug', models.SlugField(max_length=256, unique=True, verbose_name='Слаг темы')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
            },
        ),
        migrations.CreateModel(
            name='UsersOfClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_admin', models.BooleanField(default=False, verbose_name='Наличие статуса админа у пользователя клиентского форума')),
                ('username', models.CharField(max_length=255, verbose_name='Имя пользователя клиентского форума')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта пользователя клиентского форума')),
                ('password', models.CharField(max_length=24, verbose_name='Пароль пользователя клиентского форума')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL, verbose_name='Клиент пользователя')),
            ],
        ),
        migrations.CreateModel(
            name='Phors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True, verbose_name='Заголовок фора')),
                ('description', models.TextField(max_length=4096, verbose_name='Описание проблемы в форе')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания фора')),
                ('slug', models.SlugField(max_length=256, unique=True, verbose_name='Слаг фора')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phors', to='forum.usersofclient', verbose_name='Ссылка на создателя фора')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phors', to='forum.themes', verbose_name='Ссылка на тему фора')),
            ],
            options={
                'verbose_name': 'Фор',
                'verbose_name_plural': 'Форы',
                'ordering': ['date_of_creation', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=4096, verbose_name='Содержимое ответа')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания ответа')),
                ('is_correct', models.BooleanField(default=False, verbose_name="Наличие статуса 'правильный ответ' у ответа")),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='forum.usersofclient', verbose_name='Ссылка на создателя ответа')),
                ('parent_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_answers', to='forum.answers', verbose_name='Ссылка на родительский ответ ответа')),
                ('phor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='forum.phors', verbose_name='Ссылка на фор ответа')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'ordering': ['date_of_creation'],
            },
        ),
    ]
