# Generated by Django 4.0.5 on 2022-07-10 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersofclient',
            name='password',
        ),
    ]
