# Generated by Django 4.0.5 on 2022-07-12 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0002_remove_usersofclient_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogOfUserOfClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=512, verbose_name='Содержимое лога')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, verbose_name='Время создания лога')),
                ('user_of_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='forum.usersofclient', verbose_name='Пользователь клиента')),
            ],
            options={
                'verbose_name': 'Лог пользователя клиента',
                'verbose_name_plural': 'Логи пользователей клиентов',
                'ordering': ['date_of_creation', 'user_of_client__client__username', 'user_of_client__username'],
            },
        ),
        migrations.CreateModel(
            name='LogOfClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=512, verbose_name='Содержимое лога')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, verbose_name='Время создания лога')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Лог клиента',
                'verbose_name_plural': 'Логи клиентов',
                'ordering': ['date_of_creation', 'client__username'],
            },
        ),
    ]
