# Generated by Django 4.0.5 on 2022-07-08 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0002_answers_parent_answer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answers',
            options={'ordering': ['date_of_creation'], 'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterModelOptions(
            name='phors',
            options={'ordering': ['date_of_creation', 'title'], 'verbose_name': 'Фор', 'verbose_name_plural': 'Форы'},
        ),
        migrations.AlterModelOptions(
            name='themes',
            options={'verbose_name': 'Тема', 'verbose_name_plural': 'Темы'},
        ),
        migrations.AlterField(
            model_name='answers',
            name='content',
            field=models.TextField(max_length=4096, verbose_name='Содержимое ответа'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL, verbose_name='Ссылка на создателя ответа'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='date_of_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания ответа'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name="Наличие статуса 'правильный ответ' у ответа"),
        ),
        migrations.AlterField(
            model_name='answers',
            name='parent_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_answers', to='forum.answers', verbose_name='Ссылка на родительский ответ ответа'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='phor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='forum.phors', verbose_name='Ссылка на фор ответа'),
        ),
        migrations.AlterField(
            model_name='phors',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phors', to=settings.AUTH_USER_MODEL, verbose_name='Ссылка на создателя фора'),
        ),
        migrations.AlterField(
            model_name='phors',
            name='date_of_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания фора'),
        ),
        migrations.AlterField(
            model_name='phors',
            name='description',
            field=models.TextField(max_length=4096, verbose_name='Описание проблемы в форе'),
        ),
        migrations.AlterField(
            model_name='phors',
            name='slug',
            field=models.SlugField(max_length=256, unique=True, verbose_name='Слаг фора'),
        ),
        migrations.AlterField(
            model_name='phors',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phors', to='forum.themes', verbose_name='Ссылка на тему фора'),
        ),
        migrations.AlterField(
            model_name='phors',
            name='title',
            field=models.CharField(max_length=128, unique=True, verbose_name='Заголовок фора'),
        ),
        migrations.AlterField(
            model_name='themes',
            name='slug',
            field=models.SlugField(max_length=256, unique=True, verbose_name='Слаг темы'),
        ),
        migrations.AlterField(
            model_name='themes',
            name='title',
            field=models.CharField(max_length=128, unique=True, verbose_name='Название темы'),
        ),
    ]
