# Generated by Django 4.0.5 on 2022-07-12 14:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_logofuserofclient_logofclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersofclient',
            name='date_of_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания пользователя клиента'),
            preserve_default=False,
        ),
    ]
