# Generated by Django 4.0.5 on 2022-07-12 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0005_alter_usersofclient_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='themes',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='themes', to=settings.AUTH_USER_MODEL, verbose_name='Создатель темы'),
        ),
    ]
