# Generated by Django 4.0.5 on 2022-07-13 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_alter_phors_creator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answers',
            options={'ordering': ['-date_of_creation'], 'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterModelOptions(
            name='logofclient',
            options={'ordering': ['-date_of_creation', 'client__username'], 'verbose_name': 'Лог клиента', 'verbose_name_plural': 'Логи клиентов'},
        ),
        migrations.AlterModelOptions(
            name='logofuserofclient',
            options={'ordering': ['-date_of_creation', 'user_of_client__client__username', 'user_of_client__username'], 'verbose_name': 'Лог пользователя клиента', 'verbose_name_plural': 'Логи пользователей клиентов'},
        ),
        migrations.AlterModelOptions(
            name='phors',
            options={'ordering': ['-date_of_creation', 'title'], 'verbose_name': 'Фор', 'verbose_name_plural': 'Форы'},
        ),
        migrations.AlterModelOptions(
            name='usersofclient',
            options={'ordering': ['-date_of_creation', 'client', 'username'], 'verbose_name': 'Пользователь клиента', 'verbose_name_plural': 'Пользователи клиентов'},
        ),
    ]
